### ISSUE TITLE
Error when Running JAR file: java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by William-N-Havard** [christopheparisse/tei-corpo#5]
I get this error when running the JAR file to convert some documents (Windows, Java 1.8.0_381) Any way to solve this?

Command
```
java -cp teicorpo_1-41-01.jar fr.ortolang.teicorpo.TeiCorpo -from trs -to elan .\Gaspard.trs -o .\Gaspard.eaf                  
```

Output
```
TeiCorpo (version 1.41.12) 29/09/2023 11:00 Version TEI_CORPO: 0.9.1
mainCommand: (-from trs -to elan Gaspard.trs)
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/io/FileUtils
        at fr.ortolang.teicorpo.EOLUtils.convertLineEndings(EOLUtils.java:301)
        at fr.ortolang.teicorpo.EOLUtils.convertToUnixEOL(EOLUtils.java:202)
        at fr.ortolang.teicorpo.Utils.createFileTransformer(Utils.java:514)
        at fr.ortolang.teicorpo.Utils.createFile(Utils.java:492)
        at fr.ortolang.teicorpo.TranscriberToTei.mainProcess(TranscriberToTei.java:877)
        at fr.ortolang.teicorpo.TeiCorpo.process(TeiCorpo.java:134)
        at fr.ortolang.teicorpo.TeiCorpo.mainProcess(TeiCorpo.java:314)
        at fr.ortolang.teicorpo.GenericMain.processFiles(GenericMain.java:190)
        at fr.ortolang.teicorpo.GenericMain.mainCommand(GenericMain.java:62)
        at fr.ortolang.teicorpo.TeiCorpo.main(TeiCorpo.java:306)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.io.FileUtils
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 10 more
```

**Comment by William-N-Havard** [comment]
TeiCorpo (version 1.41.01) 19/04/2022 08:00 Version TEI_CORPO: 0.9.1 shipped with commit [7f39ca0](https://github.com/christopheparisse/teicorpo/commit/7f39ca039b3766627b6f862f018f0258d5250cb2) works fine but the following ones don't, so the issue arose in the following commit.
